CREATE TABLE orders(order_id INTEGER PRIMARY KEY, customer TEXT, product TEXT, category TEXT, quantity INTEGER, price INTEGER); INSERT INTO orders VALUES (1, 'Alice','Laptop', 'Electronics', 1, 25000), (2, 'Bob', 'Mouse', 'Electronics', 2, 500), (3, 'Alice', 'Keyboard', 'Electronics', 1, 1500), (4, 'John', 'Chair', 'Furniture', 2, 3000), (5, 'Bob', 'Desk', 'Furniture', 1, 5000);
SELECT COUNT (order_id) AS total_orders FROM orders; SELECT SUM(quantity * price) AS total_revenue FROM orders; SELECT customer, SUM(quantity * price) AS customer_revenue FROM orders GROUP BY customer; SELECT category, SUM(quantity * price) AS category_revenue FROM orders GROUP BY category; SELECT product, SUM(quantity * price) AS product_revenue FROM orders GROUP BY product ORDER BY product_revenue DESC LIMIT 1; 


-- ==========================================
-- Sales Analysis Project : Day 2
-- ==========================================

-- Q1: Which orders have a price above 3,000 THB?
SELECT  product, price  FROM orders WHERE price > 3000;

-- Q2: Which products have the highest prices?
SELECT * FROM orders ORDER BY price DESC LIMIT 1;

-- Q3: Which customer generates the most revenue?
SELECT customer, SUM(quantity * price) AS total_revenue FROM orders GROUP BY customer ORDER BY  total_revenue DESC LIMIT 1;

-- Q4: What is the average product price by category?
SELECT category, AVG(price) AS avg_price FROM orders GROUP BY category;

-- Q5: How many orders are in each category?
SELECT category, COUNT(*) AS Order_count FROM orders GROUP BY category;

-- Task 6: Top customer by revenue
SELECT customer, SUM(quantity * price) AS total_revenue FROM orders GROUP BY customer ORDER BY  total_revenue DESC LIMIT 1;





-- Q1: Filter for records where the product price is less than 3,000 THB.
SELECT
    * 
    -- Retrieved data across all available columns
FROM
    orders -- Specified the target orders table
WHERE
    price < 3000; -- Filtered records for products priced under 3000 THB


/* 
💡 PRESENTATION NOTES & THAI TRANSLATION:
- Script: "This query | retrieved all data | from the orders table, | and then filtered records | for products priced under | 3,000 THB."
- คำอ่าน: ดิส ควิ-รี่ | รี-ทรีฟว์ ออล ดา-ต้า | ฟรอม ดิ ออร์-เดอร์ส เท-เบิล | แอนด์ เด็น ฟิล-เทอร์ด เรค-คอร์ดส | ฟอร์ พรอ-ดักท์ส ไพรซ์ อัน-เดอร์ | ตรี-ทาว-ซันด์ ที-เอช-บี
- แปลไทย: คิวรี่นี้ | ดึงข้อมูลทั้งหมด | จากตาราง orders | แล้วทำการกรองข้อมูลเอาเฉพาะแถว | ของสินค้าที่มีราคาต่ำกว่า | 3,000 บาท
*/



-- Q2: Retrieve all products and sort them by quantity in descending order.
SELECT
    * -- Retrieved data across all available columns
FROM
    orders -- Specified the target orders table
ORDER BY
    quantity DESC; -- Sorted records based on volume from highest to lowest

/* 
💡 PRESENTATION NOTES & THAI TRANSLATION:
- Script: "This query | retrieved all data | from the orders table, | and then sorted all records | by quantity | from highest to lowest."
- คำอ่าน: ดิส ควิ-รี่ | รี-ทรีฟว์ ออล ดา-ต้า | ฟรอม ดิ ออร์-เดอร์ส เท-เบิล | แอนด์ เด็น ซอร์-เทด ออล เรค-คอร์ดส | บาย ควอน-ติ-ตี้ | ฟรอม ไฮ-เอสท์ ทู โล-เวสท์
- แปลไทย: คิวรี่นี้ | ดึงข้อมูลทั้งหมด | จากตาราง orders | แล้วทำการจัดเรียงข้อมูลทั้งหมด | ตามจำนวนชิ้น | จากมากที่สุดไปหาน้อยที่สุด

พูด: "This query | retrieved all data | from the orders table, | and then sorted all records | by quantity | from highest to lowest."
อ่าน: ดิส ควิ-รี่ | รี-ทรีฟว์ ออล ดา-ต้า | ฟรอม ดิ ออร์-เดอร์ส เท-เบิล | แอนด์ เด็น ซอร์-เทด ออล เรค-คอร์ดส | บาย ควอน-ติ-ตี้ | ฟรอม ไฮ-เอสท์ ทู โล-เวสท์
แปล: คิวรี่นี้ | ดึงข้อมูลทั้งหมด | จากตาราง orders | แล้วทำการจัดเรียงข้อมูลทั้งหมด | ตามปริมาณจำนวนชิ้น | จากมากที่สุดไปหาน้อยที่สุดครับ
*/

-- -- Q3: Calculate the aggregate sum of all product quantities sold.
SELECT
    SUM(quantity) AS total_quantity_sold -- Aggregated the total volume of items sold
FROM
    orders; -- Specified the target orders table

/* 
💡 PRESENTATION NOTES & THAI TRANSLATION:
- Script: "This query | used the SUM function | to calculate the aggregate volume | of all products sold."
- คำอ่าน: ดิส ควิ-รี่ | ยูสด์ เดอะ ซัม ฟังก์ชัน | ทู แคล-คู-เลท ดิ แอก-กรี-เกท วอล-ลุ่ม | ออฟ ออล พรอ-ดักท์ส โซลด์
- แปลไทย: คิวรี่นี้ | ใช้ฟังก์ชัน SUM | เพื่อคำนวณหาปริมาณผลรวมสะสม | ของสินค้าทั้งหมดที่ขายได้ */


-- Q4: Calculate the total revenue generated by each product.
SELECT
    product, -- Selected the product name column
    SUM(quantity * price) AS total_revenue -- Calculated the total revenue per product
FROM
    orders -- Specified the target orders table
GROUP BY
    product; -- Grouped the aggregated data by product

/* 
💡 PRESENTATION NOTES & THAI TRANSLATION:
- Script: "This query | calculated the total revenue | for each product | by multiplying quantity and price, | and then grouping the results."
- คำอ่าน: ดิส ควิ-รี่ | แคล-คู-เล-เตด เดอะ โท-เทิล เร-เว-นิว | ฟอร์ อีช พรอ-ดักท์ | บาย มัล-ติ-พลาย-อิง ควอน-ติ-ตี้ แอนด์ ไพรซ์ | แอนด์ เด็น กรุ๊ป-ปิง เดอะ รี-ซัลท์ส
- แปลไทย: คิวรี่นี้ | คำนวณรายได้รวมทั้งหมด | ของสินค้าแต่ละชิ้น | โดยการคูณจำนวนชิ้นกับราคา | แล้วนำผลลัพธ์มาจัดกลุ่มแยกจากกัน
*/


-- Q5: Identify the customer who generated the lowest total revenue.  -- แปลภาษาคน: ระบุตัวตนลูกค้า | คนที่สร้าง | รายได้รวมต่ำที่สุด
SELECT
    customer, -- Selected the customer name column
    SUM(quantity * price) AS total_revenue -- Calculated the total revenue per customer
FROM
    orders -- Specified the target orders table
GROUP BY
    customer -- Grouped the aggregated data by customer
ORDER BY
    total_revenue ASC -- Sorted revenue from lowest to highest
LIMIT 1; -- Retrieved only the bottom customer with lowest revenue


/* 
💡 PRESENTATION NOTES & THAI TRANSLATION:
- Script: "This query | calculated total revenue | per customer, | sorted the results | from lowest to highest, | and used LIMIT 1 | to find the customer with the lowest spending."
- คำอ่าน: ดิส ควิ-รี่ | แคล-คู-เล-เตด โท-เทิล เร-เว-นิว | เพอร์ คัส-โต-เมอร์ | ซอร์-เทด เดอะ รี-ซัลท์ส | ฟรอม โล-เวสท์ ทู ไฮ-เอสท์ | แอนด์ ยูสด์ ลิ-มิท วัน | ทู ไฟนด์ เดอะ คัส-โต-เมอร์ วิธ เดอะ โล-เวสท์ สเปน-ดิง
- แปลไทย: คิวรี่นี้ | คำนวณรายได้รวม | แยกตามลูกค้าแต่ละราย | แล้วจัดเรียงผลลัพธ์ | จากน้อยที่สุดไปมากที่สุด | จากนั้นใช้คำสั่ง LIMIT 1 | เพื่อหาลูกค้าที่มีการใช้จ่ายรวมต่ำที่สุด
*/



SELECT 
    product,
    price,
    -- Evaluate product prices into customized logical tiers
    CASE 
        WHEN price >= 5000 THEN 'High'
        WHEN price = 0 THEN 'Free'
        ELSE 'Normal'
    END AS price_level
FROM orders;


SELECT 
    customer,
    -- Calculate total revenue using quantity multiplied by unit price
    SUM(quantity * price) AS total_revenue
FROM orders
GROUP BY customer
HAVING SUM(quantity * price) > 5000; -- HAVING filters the total amount after checking out.
/* "We used the HAVING clause to filter customers based on their aggregated total revenue." */


SELECT 
    customer,
    SUM(quantity * price) AS total_revenue
FROM orders
GROUP BY customer
HAVING SUM(quantity * price) > 5000
ORDER BY total_revenue DESC;
/* This query ranks our highest-spending customers first */